timeframes:
  MN1:
    max_lookback: 12
  W1:
    max_lookback: 24
  D1:
    max_lookback: 50
  H4:
    max_lookback: 100
  H1:
    max_lookback: 200
  M15:
    max_lookback: 400
  M5:
    max_lookback: 600
  M1:
    max_lookback: 1000

# Broker-specific symbol suffix
# Examples:
# - For suffix 'm': "EURUSDm"
# - For suffix '.r': "EURUSD.r"
# - For no suffix: leave empty
symbol_suffix:

symbols:
  major_pairs:
    - "EURUSD.sml"
    - "USDJPY.sml"
    - "GBPUSD.sml"
    - "USDCHF"
    - "USDCAD"
    - "AUDUSD.sml"
    - "NZDUSD"
  crosses:
    - "AUDCAD"
    - "AUDCHF"
    - "AUDJPY"
    - "AUDNZD"
    - "CADCHF"
    - "CADJPY"
    - "CHFJPY"
    - "EURAUD"
    - "EURCAD"
    - "EURCHF"
    - "EURGBP.sml"
    - "EURJPY"
    - "EURNZD"
    - "GBPAUD"
    - "GBPCAD"
    - "GBPCHF"
    - "GBPJPY.sml"
    - "GBPNZD"
    - "NZDCAD"
    - "NZDCHF"
    - "NZDJPY"
  metals:
    - "XAUUSD.sml"
    - "XAGUSD"
  crypto:
    - "BTCUSD"
    - "ETHUSD"

fvg_settings:
  min_size:
    default: 0.0001
    metals: 0.1
    crypto: 10.0

telegram:
  enabled: true